financial_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import financial_system

urlpatterns = [
    path('', include('financial_system.urls', namespace='financial_system')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financial_system/urls.py
from django.urls import path
from . import views

app_name = 'financial_system'
urlpatterns = [
    path('', views.news_view, name='index'),
    path('sign_up/', views.sign_up_view, name='sign_up'),
    path('register_action/', views.register_action, name='register_action'),
    path('login/', views.login_view, name='login'),
    path('login_action/', views.login_action, name='login_action'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.user_profile_view, name='user_profile'),
    path('edit_profile_action/', views.edit_user_profile_action, name='edit_user_profile_action'),

    path('watchlist/', views.user_watchlist_view, name='user_watchlist_view'),
    path('watchlist/<str:stock_symbol>', views.user_watchlist_view, name='user_watchlist_id_view'),
    #user_watchlist_monitor
    path('watchlist/monitor/', views.user_watchlist_monitor, name='user_watchlist_monitor'),

    path('add_to_watchlist/<str:stock_symbol>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/<str:stock_symbol>/', views.remove_from_watchlist, name='remove_from_watchlist'),

    path('stocks/', views.stock_list_view, name='stock_list'),
    path('stock/<str:stock_symbol>', views.stock_detail_view, name='stock_detail'),
    path('stock_current_price/', views.stock_current_price, name='stock_current_price'),

    path('trade/<str:stock_symbol>', views.trade, name='trade'),
    path('buy_stock/', views.buy_stock, name='buy_stock'),
    path('sell_stock/', views.sell_stock, name='sell_stock'),

    path('stock/<str:stock_symbol>/add_comment/', views.add_comment, name='add_comment'),
    path('comments/add_reply/', views.add_reply, name='add_reply'),


    path('notifications/', views.user_notification_view, name='user_notification'),

    path('balance/', views.balance, name='balance'),
    path('deposit_funds/', views.deposit_funds, name='deposit_funds'),
    path('withdraw_funds/', views.withdraw_funds, name='withdraw_funds'),

    path('news/', views.news_view, name='news'),
    path('news/<int:news_id>/', views.news_detail_view, name='news_detail'),

    path('search_results/', views.search_view, name='search'),

    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),

    path('base', views.base, name='base'),
]

templates/elements/footer.html
{% load static %}
<div class="footer">
{#    <div class="copyright">#}
{#        <p>Copyright © Designed &amp; Developed by My Stock<span class="current-year">2024</span>#}
{#        </p>#}
{#    </div>#}
</div>

templates/elements/header.html
{% load static %}
<div class="header">
    <div class="header-content">
        <nav class="navbar navbar-expand">
            <div class="collapse navbar-collapse justify-content-between">
                <div class="header-left">
                    <a href="{% url 'financial_system:user_watchlist_view' %}" class="brand-logo">
                        <img src="{% static 'financial/images/logo-white.png' %}" alt="">

                    </a>
                </div>
                <ul class="navbar-nav header-right">


                    {% if current_user %}
                        <li class="nav-item dropdown notification_dropdown">
                            <a class="nav-link" href="javascript:void(0);" role="button" data-bs-toggle="dropdown">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                     width="32px" height="32px" viewBox="0 0 24 24" version="1.1" class="svg-main-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <path d="M17,12 L18.5,12 C19.3284271,12 20,12.6715729 20,13.5 C20,14.3284271 19.3284271,15 18.5,15 L5.5,15 C4.67157288,15 4,14.3284271 4,13.5 C4,12.6715729 4.67157288,12 5.5,12 L7,12 L7.5582739,6.97553494 C7.80974924,4.71225688 9.72279394,3 12,3 C14.2772061,3 16.1902508,4.71225688 16.4417261,6.97553494 L17,12 Z"
                                              fill="#fff"/>
                                        <rect fill="#fff" opacity="0.3" x="10" y="16" width="4" height="4" rx="2"/>
                                    </g>
                                </svg>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end">
                                <div id="DZ_W_Notification3" class="widget-media dlab-scroll p-3" style="min-height:100px;max-height: 300px;">
                                    <ul class="timeline">
                                        {% if cur_notifications %}
                                            {% for notification in cur_notifications %}
                                                <li>
                                                    <div class="timeline-panel">

                                                        <div class="media-body">
                                                            <h4 class="mb-1">Title:{{ notification.title }}</h4>
                                                            <h6 class="mb-1">Message:{{ notification.message|linebreaks }}</h6>
                                                            <small class="d-block">Date: {{ notification.created_at|date:"Y-m-d H:i:s" }}</small>
                                                            <small class="d-block">Status:{% if notification.read %}Read{% else %}Unread{% endif %}</small>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        {% else %}
                                            <h5>You have no notifications.</h5>
                                        {% endif %}
                                    </ul>
                                </div>
                                <a class="all-notification" href="{% url 'financial_system:user_notification' %}">See all notifications <i
                                        class="ti-arrow-end"></i></a>
                            </div>
                        </li>
                        <li>
                            <div class="dropdown header-profile2">
                                <a class="nav-link" href="javascript:void(0);" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <div class="header-info2 d-flex align-items-center">
                                        <div class="d-flex align-items-center sidebar-info">
                                            <div>
                                                <h4 class="text-white mb-1">{{ current_user.user_name }}</h4>
                                                <span class="d-block text-end">{{ current_user.user_email }}</span>
                                            </div>
                                        </div>
                                        <img src="{% if current_user.photo_url %}{{ current_user.photo_url }}{% else %}{% static 'financial/images/user.jpg' %}{% endif %}" alt="">
                                    </div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end" style="">
                                    <a href="{% url 'financial_system:user_profile' %}" class="dropdown-item ai-icon ">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink"
                                             width="24px" height="24px" viewBox="0 0 24 24" version="1.1"
                                             class="svg-main-icon">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <polygon points="0 0 24 0 24 24 0 24"/>
                                                <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z"
                                                      fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                                <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z"
                                                      fill="var(--primary)" fill-rule="nonzero"/>
                                            </g>
                                        </svg>
                                        <span class="ms-2">Profile </span>
                                    </a>
                                    <a href="{% url 'financial_system:logout' %}" class="dropdown-item ai-icon">
                                        <svg class="logout" xmlns="http://www.w3.org/2000/svg" width="18" height="18"
                                             viewBox="0 0 24 24" fill="none" stroke="#fd5353" stroke-width="2"
                                             stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                            <polyline points="16 17 21 12 16 7"></polyline>
                                            <line x1="21" y1="12" x2="9" y2="12"></line>
                                        </svg>
                                        <span class="ms-2 text-danger">Logout </span>
                                    </a>
                                </div>
                            </div>
                        </li>
                    {% else %}
                        <!-- Show login and registration buttons -->

                        <a class="btn tp-btn btn-secondary" href="{% url 'financial_system:login' %}">Login</a>
                        <a class="btn tp-btn btn-danger" href="{% url 'financial_system:sign_up' %}">Register</a>
                    {% endif %}


                </ul>
            </div>
        </nav>
    </div>
    <div class="page-titles" style="padding:0px;">

    </div>
</div>

templates/elements/nav-header.html
{% load static %}
<div class="nav-header" style="background-color: var(--headerbg);">


</div>

templates/elements/nav-tool.html
<div class="col-xl-12">
    <div class="coin-warpper d-flex align-items-center justify-content-between flex-wrap">
        <div>
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a href="{% url 'financial_system:news' %}" class="nav-link "
                       id="nav-news-tab">
                        News
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'financial_system:stock_list' %}" class="nav-link "
                       id="nav-market-tab">
                        Stock Market
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'financial_system:user_watchlist_view' %}"
                       class="nav-link ms-0 " id="nav-trading-tab">
                        Trading & Watchlist
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'financial_system:balance' %}" class="nav-link "
                       id="nav-market-tab">
                        Balance
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'financial_system:user_profile' %}" class="nav-link "
                       id="nav-account-tab">
                        Profile
                    </a>
                </li>

            </ul>
        </div>
        <form id="searchForm" action="{% url 'financial_system:search' %}" method="get"
              class="input-group search-area w-auto coin-tab-search mt-xl-0 mt-2">
            <input type="text" name="query" class="form-control" placeholder="">
            <span class="input-group-text"><a href="javascript:;"
                                              onclick="document.getElementById('searchForm').submit();">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                 width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="svg-main-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect x="0" y="0" width="24" height="24"/>
                                    <path d="M14.2928932,16.7071068 C13.9023689,16.3165825 13.9023689,15.6834175 14.2928932,15.2928932 C14.6834175,14.9023689 15.3165825,14.9023689 15.7071068,15.2928932 L19.7071068,19.2928932 C20.0976311,19.6834175 20.0976311,20.3165825 19.7071068,20.7071068 C19.3165825,21.0976311 18.6834175,21.0976311 18.2928932,20.7071068 L14.2928932,16.7071068 Z"
                                          fill="var(--text-dark)" fill-rule="nonzero" opacity="0.3"/>
                                    <path d="M11,16 C13.7614237,16 16,13.7614237 16,11 C16,8.23857625 13.7614237,6 11,6 C8.23857625,6 6,8.23857625 6,11 C6,13.7614237 8.23857625,16 11,16 Z M11,18 C7.13400675,18 4,14.8659932 4,11 C4,7.13400675 7.13400675,4 11,4 C14.8659932,4 18,7.13400675 18,11 C18,14.8659932 14.8659932,18 11,18 Z"
                                          fill="var(--text-dark)" fill-rule="nonzero"/>
                                </g>
                            </svg>
                        </a></span>
        </form>
    </div>
</div>

templates/elements/sidebar.html
<!--**********************************
    Sidebar start
***********************************-->
<div class="dlabnav">
    <div class="feature-box style-3">
        <div class="wallet-box">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50px"
                 height="50px" viewBox="0 0 24 24" version="1.1" class="svg-main-icon">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <rect x="0" y="0" width="24" height="24"/>
                    <circle fill="#fff" opacity="0.3" cx="20.5" cy="12.5" r="1.5"/>
                    <rect fill="#fff" opacity="0.3"
                          transform="translate(12.000000, 6.500000) rotate(-15.000000) translate(-12.000000, -6.500000) "
                          x="3" y="3" width="18" height="7" rx="1"/>
                    <path d="M22,9.33681558 C21.5453723,9.12084552 21.0367986,9 20.5,9 C18.5670034,9 17,10.5670034 17,12.5 C17,14.4329966 18.5670034,16 20.5,16 C21.0367986,16 21.5453723,15.8791545 22,15.6631844 L22,18 C22,19.1045695 21.1045695,20 20,20 L4,20 C2.8954305,20 2,19.1045695 2,18 L2,6 C2,4.8954305 2.8954305,4 4,4 L20,4 C21.1045695,4 22,4.8954305 22,6 L22,9.33681558 Z"
                          fill="#fff"/>
                </g>
            </svg>
            <div class="ms-3">
                <h4 class="text-white mb-0">$2353.25</h4>
                <small>Account total</small>
            </div>
        </div>
    </div>

    <div class="menu-scroll">
        <div class="dlabnav-scroll">
            <ul class="metismenu" id="menu">
                <li class="mm-active"><a href="{% url 'financial_system:user_watchlist_view' %}"
                                         aria-expanded="false">
                    <i class="material-symbols-outlined">dashboard</i>
                    <span class="nav-text">Dashboard</span>
                </a>

                </li>
            </ul>

            <ul class="metismenu" id="menu">
                <li class="mm-active"><a href="{% url 'financial_system:user_watchlist_view' %}"
                                         aria-expanded="false">
                    <i class="fa-regular fa-gear fw-bold"></i>

                    <span class="nav-text">Profile</span>
                </a>

                </li>
            </ul>
            <ul class="metismenu" id="menu">
                <li class="mm-active"><a href="{% url 'financial_system:user_watchlist_view' %}"
                                         aria-expanded="false">
                    <i class="material-symbols-outlined">widgets</i>
                    <span class="nav-text">Setting</span>
                </a>

                </li>
            </ul>
            <ul class="metismenu" id="menu">

                <li class="mm-active">
                    <a href="javascript:void(0);" class="bell-link"
                                         aria-expanded="false">
                        <i class="material-symbols-outlined">lab_profile</i>
                        <span class="nav-text">Chat</span>
                    </a>

                </li>
            </ul>
{#            <div class="copyright">#}
{#                <p><strong>MYSTOCK</strong> © <span class="current-year">2024</span> All Rights Reserved</p>#}
{#                <p class="fs-12">Made with <span class="heart"></span> MYSTOCK</p>#}
{#            </div>#}
        </div>
    </div>
</div>