financial_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import financial_system

urlpatterns = [
    path('', include('financial_system.urls', namespace='financial_system')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financial_system/urls.py
from django.urls import path
from . import views

app_name = 'financial_system'
urlpatterns = [
    path('', views.news_view, name='index'),
    path('sign_up/', views.sign_up_view, name='sign_up'),
    path('register_action/', views.register_action, name='register_action'),
    path('login/', views.login_view, name='login'),
    path('login_action/', views.login_action, name='login_action'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.user_profile_view, name='user_profile'),
    path('edit_profile_action/', views.edit_user_profile_action, name='edit_user_profile_action'),

    path('watchlist/', views.user_watchlist_view, name='user_watchlist_view'),
    path('watchlist/<str:stock_symbol>', views.user_watchlist_view, name='user_watchlist_id_view'),
    #user_watchlist_monitor
    path('watchlist/monitor/', views.user_watchlist_monitor, name='user_watchlist_monitor'),

    path('add_to_watchlist/<str:stock_symbol>/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/<str:stock_symbol>/', views.remove_from_watchlist, name='remove_from_watchlist'),

    path('stocks/', views.stock_list_view, name='stock_list'),
    path('stock/<str:stock_symbol>', views.stock_detail_view, name='stock_detail'),
    path('stock_current_price/', views.stock_current_price, name='stock_current_price'),

    path('trade/<str:stock_symbol>', views.trade, name='trade'),
    path('buy_stock/', views.buy_stock, name='buy_stock'),
    path('sell_stock/', views.sell_stock, name='sell_stock'),

    path('stock/<str:stock_symbol>/add_comment/', views.add_comment, name='add_comment'),
    path('comments/add_reply/', views.add_reply, name='add_reply'),


    path('notifications/', views.user_notification_view, name='user_notification'),

    path('balance/', views.balance, name='balance'),
    path('deposit_funds/', views.deposit_funds, name='deposit_funds'),
    path('withdraw_funds/', views.withdraw_funds, name='withdraw_funds'),

    path('news/', views.news_view, name='news'),
    path('news/<int:news_id>/', views.news_detail_view, name='news_detail'),

    path('search_results/', views.search_view, name='search'),

    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),

    path('base', views.base, name='base'),
]

templates/balance.html
{% extends 'base.html' %}
{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}

    <!--**********************************
        Content body start
    ***********************************-->
    <div class="content-body">
        <!-- row -->
        <div class="container-fluid">

            <div class="row">

                {% include 'elements/nav-tool.html' %}

            </div>

            <!-- notice-->
            <div class="row">
                <div class="col-xl-4 mx-auto text-center">
                    <div class="wallet-card">
                        <div class="wallet-wrapper" style="padding:3rem;">
                            <div class="mb-3" style="z-index:9999;">
                                <h2 class="fs-18 font-w400 mb-0 text-white" >My Balance</h2><br>
                                <h1 class="fs-38 font-w600 text-white" >{{ user.account_balance|floatformat:4 }}</h1>
                            </div>
                            <div class="text-end mb-2">
                                <span>
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                         height="24px" viewBox="0 0 24 24" version="1.1" class="svg-main-icon">
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                            <rect x="0" y="0" width="24" height="24"/>
                                            <rect fill="#ffff" opacity="0.3" x="12" y="4" width="3" height="13" rx="1.5"/>
                                            <rect fill="#ffff" opacity="0.3" x="7" y="9" width="3" height="8" rx="1.5"/>
                                            <path d="M5,19 L20,19 C20.5522847,19 21,19.4477153 21,20 C21,20.5522847 20.5522847,21 20,21 L4,21 C3.44771525,21 3,20.5522847 3,20 L3,4 C3,3.44771525 3.44771525,3 4,3 C4.55228475,3 5,3.44771525 5,4 L5,19 Z"
                                                  fill="#ffff" fill-rule="nonzero"/>
                                            <rect fill="#ffff" opacity="0.3" x="17" y="11" width="3" height="6" rx="1.5"/>
                                        </g>
                                    </svg>
                                </span>
                                <span class="fs-14 d-block">  </span>
                            </div>
                        </div>
                        <div class="change-btn-1">
                            <a href="javascript:void(0);" class="btn btn-lg" data-bs-toggle="modal"
                               data-bs-target="#exampleModal1">
                                <svg class="me-2 svg-main-icon" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" width="20px" height="20px"
                                     viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24"/>
                                        <path d="M2,13 C2,12.5 2.5,12 3,12 C3.5,12 4,12.5 4,13 C4,13.3333333 4,15 4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 C2,15 2,13.3333333 2,13 Z"
                                              fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                        <rect fill="#000000" opacity="0.3"
                                              transform="translate(12.000000, 8.000000) rotate(-180.000000) translate(-12.000000, -8.000000) "
                                              x="11" y="1" width="2" height="14" rx="1"/>
                                        <path d="M7.70710678,15.7071068 C7.31658249,16.0976311 6.68341751,16.0976311 6.29289322,15.7071068 C5.90236893,15.3165825 5.90236893,14.6834175 6.29289322,14.2928932 L11.2928932,9.29289322 C11.6689749,8.91681153 12.2736364,8.90091039 12.6689647,9.25670585 L17.6689647,13.7567059 C18.0794748,14.1261649 18.1127532,14.7584547 17.7432941,15.1689647 C17.3738351,15.5794748 16.7415453,15.6127532 16.3310353,15.2432941 L12.0362375,11.3779761 L7.70710678,15.7071068 Z"
                                              fill="#000000" fill-rule="nonzero"
                                              transform="translate(12.000004, 12.499999) rotate(-180.000000) translate(-12.000004, -12.499999) "/>
                                    </g>
                                </svg>
                                Deposit</a>
                            <a href="javascript:void(0);" class="btn  btn-lg" data-bs-toggle="modal"
                               data-bs-target="#exampleModal2">
                                <svg class="me-2 svg-main-icon" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" width="20px" height="20px"
                                     viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24"/>
                                        <path d="M2,13 C2,12.5 2.5,12 3,12 C3.5,12 4,12.5 4,13 C4,13.3333333 4,15 4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 C2,15 2,13.3333333 2,13 Z"
                                              fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                        <rect fill="#000000" opacity="0.3" x="11" y="2" width="2" height="14" rx="1"/>
                                        <path d="M12.0362375,3.37797611 L7.70710678,7.70710678 C7.31658249,8.09763107 6.68341751,8.09763107 6.29289322,7.70710678 C5.90236893,7.31658249 5.90236893,6.68341751 6.29289322,6.29289322 L11.2928932,1.29289322 C11.6689749,0.916811528 12.2736364,0.900910387 12.6689647,1.25670585 L17.6689647,5.75670585 C18.0794748,6.12616487 18.1127532,6.75845471 17.7432941,7.16896473 C17.3738351,7.57947475 16.7415453,7.61275317 16.3310353,7.24329415 L12.0362375,3.37797611 Z"
                                              fill="#000000" fill-rule="nonzero"/>
                                    </g>
                                </svg>
                                Withdraw</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- notice end-->

        </div>
    </div>


    <!-- modal-box-strat -->
    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form method="post" action="{% url 'financial_system:withdraw_funds' %}">
                    {% csrf_token %}
                    <div class="modal-header ">
                        <h5 class="modal-title">Withdraw</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <label class="form-label">Amount</label>
                        <input type="number" class="form-control mb-3" id="amount" name="amount"
                               placeholder="Amount">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger light" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal1" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form method="post" action="{% url 'financial_system:deposit_funds' %}">
                    {% csrf_token %}
                    <div class="modal-header ">
                        <h5 class="modal-title">Deposit</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <label class="form-label">Amount</label>
                        <input type="number" class="form-control mb-3" id="amount" name="amount"
                               placeholder="Amount">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger light" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!--**********************************
        Content body end
    ***********************************-->

{% endblock %}

{% block additional_js %}

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    {% load static custom_tags %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ dz_array.public.description }}"/>
    <meta property="og:title" content="{{ dz_array.public.og_title }}"/>
    <meta property="og:description" content="{{ dz_array.public.og_description }}"/>
    <meta property="og:image" content="{{ dz_array.public.og_image }}"/>
    <meta name="format-detection" content="telephone=no">

    <!-- PAGE TITLE HERE -->
    <title>{{ dz_array.public.title }}</title>

    <!-- 根据页面加载资源-->
    {% for cssurl in dz_array.pagelevel.financial.financial_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}">
    {% endfor %}
   <!-- 公共的css文件-->
    {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}">
    {% endfor %}
    {% block additional_css %}
    {% endblock %}

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">

</head>

<body class="body">
<div class="authincation d-flex flex-column flex-lg-row flex-column-fluid">
    <div class="login-aside text-center  d-flex flex-column flex-row-auto">
        <div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
            <div class="text-center mb-lg-4 mb-2 pt-5 logo">
                <img src="{% static 'financial/images/logo-white.png' %}" alt="">
            </div>
            <h3 class="mb-2 text-white">Welcome back!</h3>
            <p class="mb-4">Stock Trading <br>Strategy Solutions</p>
        </div>
        <div class="aside-image position-relative"
             style="background-image:url({% static 'financial/images/background/pic-2.png' %});">
            <img class="img1 move-1" src="{% static 'financial/images/background/pic3.png' %}" alt="">
            <img class="img2 move-2" src="{% static 'financial/images/background/pic4.png' %}" alt="">
            <img class="img3 move-3" src="{% static 'financial/images/background/pic5.png' %}" alt="">

        </div>
    </div>
    <div class="container flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
        <div class="d-flex justify-content-center h-100 align-items-center">
            <div class="authincation-content style-2">
                <div class="row no-gutters">
                    <div class="col-xl-12 tab-content">
                        <div id="sign-up" class="auth-form tab-pane fade show active  form-validation">
                            <form method="post" action="{% url 'financial_system:login_action' %}">
                            {% csrf_token %}
                                <div class="text-center mb-4">
                                    <h3 class="text-center mb-2 text-dark">Login</h3>
                                </div>
                                <div class="row mb-4">
                                    <div class="col-xl-6 col-12">
                                    </div>
                                    <div class="col-xl-6 col-12">

                                    </div>
                                </div>
                                <div class="sepertor">
                                    <span class="d-block mb-4 fs-13">with Phone Number</span>
                                </div>


                                {% if messages %}
                                    {% for message in messages %}
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor"
                                             stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"
                                             class="me-2 alert-icon">
                                            <polygon
                                                    points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                                            <line x1="15" y1="9" x2="9" y2="15"></line>
                                            <line x1="9" y1="9" x2="15" y2="15"></line>
                                        </svg>
                                        <strong>Error!</strong> {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                aria-label="btn-close">
                                        </button>
                                    </div>
                                {% endfor %}
                                {% endif %}


                                <div class="mb-3">
                                    <label for="exampleFormControlInput1" class="form-label required">Phone Number
                                        </label>
                                    <input type="text" class="form-control" id="phone_number" name="phone_number"
                                           value="">
                                </div>
                                <div class="mb-3 position-relative">
                                    <label class="form-label required">Password</label>
                                    <input type="password" id="password" name="password" class="form-control" value="">
                                    <span class="show-pass eye">
											<i class="fa fa-eye-slash"></i>
											<i class="fa fa-eye"></i>

										</span>
                                </div>
                                <div class="form-row d-flex justify-content-between mt-4 mb-2">

                                    <div class="mb-4">

                                    </div>
                                </div>
                                <button class="btn btn-block btn-primary">Sign In</button>

                            </form>
                            <div class="new-account mt-3 text-center">
                                    <p class="font-w500">Don’t have an account? <a class="text-primary" href="{% url 'financial_system:sign_up' %}" data-toggle="tab">Sign up</a></p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-center">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
    <script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.financial.financial_views.js|getdata:request.path %}
    <script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
    <script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/sign_up.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    {% load static custom_tags %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ dz_array.public.description }}"/>
    <meta property="og:title" content="{{ dz_array.public.og_title }}"/>
    <meta property="og:description" content="{{ dz_array.public.og_description }}"/>
    <meta property="og:image" content="{{ dz_array.public.og_image }}"/>
    <meta name="format-detection" content="telephone=no">


    <!-- PAGE TITLE HERE -->
    <title>{{ dz_array.public.title }}</title>

    {% for cssurl in dz_array.pagelevel.financial.financial_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}">
    {% endfor %}
    {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}">
    {% endfor %}
    {% block additional_css %}
    {% endblock %}
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">

</head>

<body class="body">
<div class="authincation d-flex flex-column flex-lg-row flex-column-fluid">
    <div class="login-aside text-center  d-flex flex-column flex-row-auto">
        <div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
            <div class="text-center mb-lg-4 mb-2 pt-5 logo">
                <img src="{% static 'financial/images/logo-white.png' %}" alt="">
            </div>
            <h3 class="mb-2 text-white">Welcome back!</h3>
            <p class="mb-4"> <br></p>
        </div>
        <div class="aside-image position-relative"
             style="background-image:url({% static 'financial/images/background/pic-2.png' %});">
            <img class="img1 move-1" src="{% static 'financial/images/background/pic3.png' %}" alt="">
            <img class="img2 move-2" src="{% static 'financial/images/background/pic4.png' %}" alt="">
            <img class="img3 move-3" src="{% static 'financial/images/background/pic5.png' %}" alt="">

        </div>
    </div>
    <div class="container flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
        <div class="d-flex justify-content-center h-100 align-items-center">
            <div class="authincation-content style-2">
                <div class="row no-gutters">
                    <div class="col-xl-12 tab-content">
                        <div id="sign-up" class="auth-form tab-pane fade show active form-validation">

                            <form action="{% url 'financial_system:register_action' %}" method="post">

                                {% csrf_token %}

                                <div class="text-center mb-4">
                                    <h3 class="text-center mb-2 text-dark">Sign up</h3>
                                    <span></span>
                                </div>
                                <div class="row mb-4">
                                    <div class="col-xl-6 col-12">

                                    </div>
                                    <div class="col-xl-6 col-12">

                                    </div>
                                </div>
                                <div class="sepertor">
                                    <span class="d-block mb-4 fs-13"> With Phone Number </span>
                                </div>


                                {% if messages %}
                                    {% for message in messages %}
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor"
                                             stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"
                                             class="me-2 alert-icon">
                                            <polygon
                                                    points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                                            <line x1="15" y1="9" x2="9" y2="15"></line>
                                            <line x1="9" y1="9" x2="15" y2="15"></line>
                                        </svg>
                                        <strong>Error!</strong> {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                                aria-label="btn-close">
                                        </button>
                                    </div>
                                    {% endfor %}
                                {% endif %}

                                <div class="mb-3">
                                    <label for="user_name" class="form-label required">Name</label>
                                    <input type="text" class="form-control" id="user_name" name="user_name"
                                           placeholder="username">
                                </div>
                                <div class="mb-3">
                                    <label for="phone_number" class="form-label required">Phone Number</label>
                                    <input type="text" class="form-control" id="phone_number" name="phone_number"
                                           placeholder="phone number">
                                </div>
                                <div class="mb-3">
                                    <label for="user_gender" class="form-label required">Gender</label>
                                    <select class="default-select  form-control wide mb-3" id="user_gender" name="user_gender" required>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                    </select>
                                </div>

                                <div class="mb-3">
                                    <label for="user_email" class="form-label required">Email
                                        address</label>
                                    <input type="email" class="form-control" id="user_email" name="user_email"
                                           placeholder="Email">
                                </div>
                                <div class="mb-3 position-relative">
                                    <label class="form-label required">Password</label>
                                    <input type="password" id="password" class="form-control" value="" name="password">
                                    <span class="show-pass eye">
											<i class="fa fa-eye-slash"></i>
											<i class="fa fa-eye"></i>

										</span>
                                </div>

                                <button type="submit" class="btn btn-block btn-primary">Sign me up</button>

                            </form>
                            <div class="new-account mt-3 text-center">
                                <p class="font-w500">Already have an account? <a class="text-primary"
                                                                                 href="{% url 'financial_system:login' %}">Sign
                                    in</a></p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-center">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
    <script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.financial.financial_views.js|getdata:request.path %}
    <script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
    <script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/submit_feedback.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>Submit Feedback</title>{% endblock %}
{% block additional_css %}
{% endblock %}

{% block content %}

    <!--**********************************
        Content body start
    ***********************************-->
    <div class="content-body">
        <!-- row -->
        <div class="container-fluid">
            <div class="row">
               {% include 'elements/nav-tool.html' %}
            </div>
            <div class="row">
                <h2>Submit Feedback</h2>

                {% if user %}
                    <form method="post"
                          action="{% url 'financial_system:submit_feedback' %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input class="form-control" type="email"  id="email" name="email" required>
                        </div>


                        <div class="form-group">
                            <label for="title">Title:</label>
                            <input class="form-control" type="text" id="title" name="title" required>
                        </div>
                        <div class="form-group">
                            <label for="content">Content:</label>
                             <textarea class="form-control" type="text"  id="content" name="content" rows="5" required></textarea>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary " type="submit">Submit</button>
                        </div>
                    </form>
                {% else %}
                    <p>{{ message }}</p>
                {% endif %}

            </div>

        </div>
    </div>
    <!--**********************************
        Content body end
    ***********************************-->

{% endblock %}

{% block additional_js %}

{% endblock %}